# Generated by Django 5.0 on 2024-02-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_fonepaypayment_rename_user_invoice_invoiced_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
