# Generated by Django 5.0 on 2024-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_discount_is_referral_discount_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
